CREATE TABLE IF NOT EXISTS "anales_reviews" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"fase" text,
	"ronda" text,
	"titulo_envio" text,
	"id_envio" text,
	"revisor_username" text,
	"revisor_nombre" text,
	"revisor_apellidos" text,
	"identificador_orcid" text,
	"pais" text,
	"afiliacion" text,
	"correo_electronico" text,
	"intereses_revision" text,
	"fecha_asignada" text,
	"fecha_notificada" text,
	"fecha_confirmada" text,
	"fecha_completada" text,
	"sin_considerar" text,
	"fecha_recordatorio" text,
	"fecha_limite_contestacion" text,
	"dias_vencimiento_respuesta" text,
	"fecha_limite_revision" text,
	"dias_vencimiento_revision" text,
	"rechazado" text,
	"recomendacion" text,
	"comentarios_envio" text,
	"created_at" text DEFAULT CURRENT_TIMESTAMP
);
