CREATE TABLE IF NOT EXISTS "las_torres_de_lucca_articles" (
	"id_envio" text PRIMARY KEY NOT NULL,
	"titulo" text,
	"resumen" text,
	"nombre_autor_1" text,
	"apellidos_autor_1" text,
	"correo_electronico_autor_1" text,
	"titulo_seccion" text,
	"idioma" text,
	"asuntos" text,
	"estado" text,
	"url" text,
	"doi" text,
	"fecha_envio" text,
	"ultima_modificacion" text
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "las_torres_de_lucca_reviews" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"fase" text,
	"ronda" text,
	"titulo_envio" text,
	"id_envio" text,
	"revisor_username" text,
	"revisor_nombre" text,
	"revisor_apellidos" text,
	"identificador_orcid" text,
	"pais" text,
	"afiliacion" text,
	"correo_electronico" text,
	"intereses_revision" text,
	"fecha_asignada" text,
	"fecha_notificada" text,
	"fecha_confirmada" text,
	"fecha_completada" text,
	"sin_considerar" text,
	"fecha_recordatorio" text,
	"fecha_limite_contestacion" text,
	"dias_vencimiento_respuesta" text,
	"fecha_limite_revision" text,
	"dias_vencimiento_revision" text,
	"rechazado" text,
	"recomendacion" text,
	"comentarios_envio" text,
	"created_at" text DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "rpub_articles" (
	"id_envio" text PRIMARY KEY NOT NULL,
	"titulo" text,
	"resumen" text,
	"nombre_autor_1" text,
	"apellidos_autor_1" text,
	"correo_electronico_autor_1" text,
	"titulo_seccion" text,
	"idioma" text,
	"asuntos" text,
	"estado" text,
	"url" text,
	"doi" text,
	"fecha_envio" text,
	"ultima_modificacion" text
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "rpub_reviews" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"fase" text,
	"ronda" text,
	"titulo_envio" text,
	"id_envio" text,
	"revisor_username" text,
	"revisor_nombre" text,
	"revisor_apellidos" text,
	"identificador_orcid" text,
	"pais" text,
	"afiliacion" text,
	"correo_electronico" text,
	"intereses_revision" text,
	"fecha_asignada" text,
	"fecha_notificada" text,
	"fecha_confirmada" text,
	"fecha_completada" text,
	"sin_considerar" text,
	"fecha_recordatorio" text,
	"fecha_limite_contestacion" text,
	"dias_vencimiento_respuesta" text,
	"fecha_limite_revision" text,
	"dias_vencimiento_revision" text,
	"rechazado" text,
	"recomendacion" text,
	"comentarios_envio" text,
	"created_at" text DEFAULT CURRENT_TIMESTAMP
);
